spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course?createDatabaseIfNotExist=true
    username: root
    password: Vishal@2001
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8081